uploads = []
generated = []

[[outputs]]
id = "dpuCkoNXigoSswz5S5-Hf"
uri = "file://.local/exports/OrahDEX_Wikipedia_Draft.txt"
type = "text"
title = "OrahDEX — Wikipedia Article Draft (MediaWiki markup)"
logical_id = "49999625-20dc-4395-95f3-7cc2543fc447"
