name = "orahdex"
main = "./worker.js"
compatibility_date = "2026-07-30"
workers_dev = true

[[services]]
binding = "ORAHDEX_API"
service = "orahdex-api"

[assets]
directory = "./dist/public"
not_found_handling = "single-page-application"

[triggers]
crons = ["* * * * *"]
