// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hw-wallet/Ellipal.tsx": () => import("../components/mockups/hw-wallet/Ellipal.tsx"),
  "./components/mockups/hw-wallet/Ledger.tsx": () => import("../components/mockups/hw-wallet/Ledger.tsx"),
  "./components/mockups/hw-wallet/Tangem.tsx": () => import("../components/mockups/hw-wallet/Tangem.tsx"),
  "./components/mockups/hw-wallet/Trezor.tsx": () => import("../components/mockups/hw-wallet/Trezor.tsx")
};
