export interface CoinInfo {
  name: string;
  description: string;
  tags: string[];
  website?: string;
  whitepaper?: string;
}

const COIN_INFO: Record<string, CoinInfo> = {
  BTC: {
    name: "Bitcoin",
    description: "The original proof-of-work digital currency and global store of value.",
    tags: ["Layer 1", "PoW", "Store of Value"],
    website: "https://bitcoin.org",
    whitepaper: "https://bitcoin.org/bitcoin.pdf",
  },
  BSV: {
    name: "Bitcoin SV",
    description: "Satoshi's original Bitcoin vision — massively scalable, <$0.001 fees, <5s settlement.",
    tags: ["Layer 1", "PoW", "Scaling"],
    website: "https://bitcoinsv.io",
    whitepaper: "https://bitcoin.org/bitcoin.pdf",
  },
  ETH: {
    name: "Ethereum",
    description: "Programmable blockchain powering smart contracts, DeFi, and NFTs.",
    tags: ["Layer 1", "Smart Contracts", "PoS"],
    website: "https://ethereum.org",
  },
  BNB: {
    name: "BNB",
    description: "Native token of Binance Smart Chain, used for gas fees and ecosystem utilities.",
    tags: ["Layer 1", "Exchange Token", "PoSA"],
    website: "https://bnbchain.org",
  },
  SOL: {
    name: "Solana",
    description: "High-throughput blockchain with sub-second finality and extremely low fees.",
    tags: ["Layer 1", "PoH", "High Speed"],
    website: "https://solana.com",
  },
  XRP: {
    name: "XRP",
    description: "Digital payment protocol designed for fast, low-cost cross-border transactions.",
    tags: ["Payments", "Layer 1", "XRPL"],
    website: "https://ripple.com",
  },
  ADA: {
    name: "Cardano",
    description: "Peer-reviewed, research-driven Proof-of-Stake blockchain for secure dApps.",
    tags: ["Layer 1", "PoS", "Academic"],
    website: "https://cardano.org",
  },
  DOGE: {
    name: "Dogecoin",
    description: "The original meme coin — fast, fun, and widely accepted for tipping and payments.",
    tags: ["Meme", "PoW", "Payments"],
    website: "https://dogecoin.com",
  },
  DOT: {
    name: "Polkadot",
    description: "Multi-chain protocol enabling interoperability between blockchains via parachains.",
    tags: ["Layer 0", "Interoperability", "PoS"],
    website: "https://polkadot.network",
  },
  AVAX: {
    name: "Avalanche",
    description: "Ultra-fast, low-latency blockchain with a unique tri-chain architecture and subnets.",
    tags: ["Layer 1", "PoS", "Subnets"],
    website: "https://avax.network",
  },
  MATIC: {
    name: "Polygon",
    description: "Ethereum scaling solution offering fast transactions and near-zero gas fees.",
    tags: ["Layer 2", "Scaling", "Ethereum"],
    website: "https://polygon.technology",
  },
  POL: {
    name: "Polygon (POL)",
    description: "Upgraded token for the Polygon ecosystem, supporting multiple chains and validators.",
    tags: ["Layer 2", "Scaling", "Ethereum"],
    website: "https://polygon.technology",
  },
  LINK: {
    name: "Chainlink",
    description: "Decentralized oracle network connecting smart contracts to real-world data.",
    tags: ["Oracle", "DeFi Infrastructure", "Ethereum"],
    website: "https://chain.link",
  },
  UNI: {
    name: "Uniswap",
    description: "Governance token of the leading decentralized exchange protocol on Ethereum.",
    tags: ["DeFi", "DEX", "Governance"],
    website: "https://uniswap.org",
  },
  AAVE: {
    name: "Aave",
    description: "Decentralized lending and borrowing protocol with flash loan capabilities.",
    tags: ["DeFi", "Lending", "Ethereum"],
    website: "https://aave.com",
  },
  MKR: {
    name: "Maker",
    description: "Governance token for MakerDAO, the protocol behind the DAI stablecoin.",
    tags: ["DeFi", "Stablecoin", "Governance"],
    website: "https://makerdao.com",
  },
  COMP: {
    name: "Compound",
    description: "Algorithmic money market protocol enabling permissionless lending on Ethereum.",
    tags: ["DeFi", "Lending", "Ethereum"],
    website: "https://compound.finance",
  },
  CRV: {
    name: "Curve",
    description: "DEX optimized for stablecoin and similarly-priced asset swaps with minimal slippage.",
    tags: ["DeFi", "DEX", "Stablecoins"],
    website: "https://curve.fi",
  },
  SNX: {
    name: "Synthetix",
    description: "Protocol for issuing and trading synthetic assets tracking real-world prices.",
    tags: ["DeFi", "Synthetics", "Ethereum"],
    website: "https://synthetix.io",
  },
  SUSHI: {
    name: "SushiSwap",
    description: "Community-owned DEX offering swaps, yield farming, and cross-chain features.",
    tags: ["DeFi", "DEX", "Multichain"],
    website: "https://sushi.com",
  },
  LTC: {
    name: "Litecoin",
    description: "Fast, low-fee peer-to-peer cryptocurrency based on Bitcoin's codebase.",
    tags: ["Layer 1", "PoW", "Payments"],
    website: "https://litecoin.org",
  },
  BCH: {
    name: "Bitcoin Cash",
    description: "Bitcoin fork focused on cheap, fast on-chain payments for everyday use.",
    tags: ["Layer 1", "PoW", "Payments"],
    website: "https://bitcoincash.org",
  },
  ETC: {
    name: "Ethereum Classic",
    description: "Original Ethereum chain upholding code-is-law and immutability principles.",
    tags: ["Layer 1", "PoW", "Ethereum"],
    website: "https://ethereumclassic.org",
  },
  ATOM: {
    name: "Cosmos",
    description: "Hub of an internet of blockchains, enabling IBC inter-chain communication.",
    tags: ["Layer 0", "Cosmos", "IBC"],
    website: "https://cosmos.network",
  },
  NEAR: {
    name: "NEAR Protocol",
    description: "Developer-friendly blockchain with sharding for infinite scalability.",
    tags: ["Layer 1", "Sharding", "PoS"],
    website: "https://near.org",
  },
  ALGO: {
    name: "Algorand",
    description: "Carbon-neutral, pure Proof-of-Stake blockchain for finance and real-world assets.",
    tags: ["Layer 1", "PoS", "Green"],
    website: "https://algorand.foundation",
  },
  FTM: {
    name: "Fantom",
    description: "DAG-based smart contract platform delivering sub-second finality.",
    tags: ["Layer 1", "DAG", "PoS"],
    website: "https://fantom.foundation",
  },
  HBAR: {
    name: "Hedera",
    description: "Enterprise-grade hashgraph network for tokenization, data, and DeFi.",
    tags: ["Layer 1", "Hashgraph", "Enterprise"],
    website: "https://hedera.com",
  },
  ICP: {
    name: "Internet Computer",
    description: "Blockchain computer running smart contracts directly on the internet at web speed.",
    tags: ["Layer 1", "Web3", "Decentralized Cloud"],
    website: "https://internetcomputer.org",
  },
  VET: {
    name: "VeChain",
    description: "Enterprise blockchain platform for supply chain management and product tracking.",
    tags: ["Layer 1", "Enterprise", "Supply Chain"],
    website: "https://vechain.com",
  },
  EGLD: {
    name: "MultiversX",
    description: "Adaptive-state sharded blockchain built for global enterprise adoption.",
    tags: ["Layer 1", "Sharding", "Enterprise"],
    website: "https://multiversx.com",
  },
  XLM: {
    name: "Stellar",
    description: "Open network for low-cost, fast cross-border payments and asset issuance.",
    tags: ["Payments", "Layer 1", "SCP"],
    website: "https://stellar.org",
  },
  TRX: {
    name: "TRON",
    description: "High-throughput blockchain for decentralized content distribution and USDT payments.",
    tags: ["Layer 1", "DPoS", "Content"],
    website: "https://tron.network",
  },
  XTZ: {
    name: "Tezos",
    description: "Self-amending blockchain with on-chain governance and formal verification.",
    tags: ["Layer 1", "PoS", "Governance"],
    website: "https://tezos.com",
  },
  SAND: {
    name: "The Sandbox",
    description: "Virtual metaverse where players can build, own, and monetize experiences using NFTs.",
    tags: ["Metaverse", "Gaming", "NFT"],
    website: "https://sandbox.game",
  },
  MANA: {
    name: "Decentraland",
    description: "Decentralized virtual world where users buy and sell digital land as NFTs.",
    tags: ["Metaverse", "NFT", "Gaming"],
    website: "https://decentraland.org",
  },
  AXS: {
    name: "Axie Infinity",
    description: "Blockchain-based game where players earn by battling and breeding digital creatures.",
    tags: ["Gaming", "NFT", "Play-to-Earn"],
    website: "https://axieinfinity.com",
  },
  APE: {
    name: "ApeCoin",
    description: "Governance and utility token for the Bored Ape Yacht Club ecosystem and Web3 gaming.",
    tags: ["Gaming", "Metaverse", "NFT"],
    website: "https://apecoin.com",
  },
  GRT: {
    name: "The Graph",
    description: "Decentralized indexing protocol for querying blockchain data via GraphQL.",
    tags: ["DeFi Infrastructure", "Indexing", "Ethereum"],
    website: "https://thegraph.com",
  },
  LDO: {
    name: "Lido DAO",
    description: "Liquid staking protocol allowing ETH holders to stake without locking funds.",
    tags: ["DeFi", "Liquid Staking", "Ethereum"],
    website: "https://lido.fi",
  },
  OP: {
    name: "Optimism",
    description: "Ethereum Layer-2 rollup scaling network using optimistic fraud proofs.",
    tags: ["Layer 2", "Optimistic Rollup", "Ethereum"],
    website: "https://optimism.io",
  },
  ARB: {
    name: "Arbitrum",
    description: "Leading Ethereum Layer-2 using optimistic rollup for EVM-compatible scaling.",
    tags: ["Layer 2", "Optimistic Rollup", "Ethereum"],
    website: "https://arbitrum.io",
  },
  IMX: {
    name: "Immutable X",
    description: "Layer-2 for NFTs on Ethereum with zero gas fees and instant confirmations.",
    tags: ["Layer 2", "NFT", "Ethereum"],
    website: "https://immutable.com",
  },
  ZK: {
    name: "zkSync",
    description: "Ethereum Layer-2 using zero-knowledge proofs for EVM-compatible scaling.",
    tags: ["Layer 2", "ZK Rollup", "Ethereum"],
    website: "https://zksync.io",
  },
  SCR: {
    name: "Scroll",
    description: "EVM-equivalent ZK-Rollup for Ethereum with native account abstraction support.",
    tags: ["Layer 2", "ZK Rollup", "Ethereum"],
    website: "https://scroll.io",
  },
  MNT: {
    name: "Mantle",
    description: "EVM-compatible L2 with modular data availability for large-scale dApps.",
    tags: ["Layer 2", "Modular", "Ethereum"],
    website: "https://mantle.xyz",
  },
  BLUR: {
    name: "Blur",
    description: "NFT marketplace token offering aggregated trading and advanced analytics.",
    tags: ["NFT", "Marketplace", "Ethereum"],
    website: "https://blur.io",
  },
  PEPE: {
    name: "Pepe",
    description: "Meme coin inspired by the iconic internet frog — pure community hype.",
    tags: ["Meme", "Ethereum"],
    website: "https://pepe.vip",
  },
  SHIB: {
    name: "Shiba Inu",
    description: "Dogecoin-rivaling meme coin with its own DEX, metaverse, and token ecosystem.",
    tags: ["Meme", "DeFi", "Ecosystem"],
    website: "https://shibatoken.com",
  },
  FLOKI: {
    name: "FLOKI",
    description: "Meme coin with utility across play-to-earn gaming, DeFi, and NFT marketplaces.",
    tags: ["Meme", "Gaming", "DeFi"],
    website: "https://floki.com",
  },
  WIF: {
    name: "dogwifhat",
    description: "Viral Solana meme coin — a dog wearing a hat, fuelled entirely by community.",
    tags: ["Meme", "Solana"],
  },
  BONK: {
    name: "Bonk",
    description: "First community meme coin on Solana, airdropped to the ecosystem.",
    tags: ["Meme", "Solana"],
    website: "https://bonkcoin.com",
  },
  USDT: {
    name: "Tether USD",
    description: "The largest dollar-backed stablecoin, pegged 1:1 to the US Dollar.",
    tags: ["Stablecoin", "USD", "Fiat-backed"],
    website: "https://tether.to",
  },
  USDC: {
    name: "USD Coin",
    description: "Regulated fiat-backed stablecoin issued by Circle, redeemable 1:1 for USD.",
    tags: ["Stablecoin", "USD", "Regulated"],
    website: "https://circle.com/usdc",
  },
  DAI: {
    name: "Dai",
    description: "Decentralized crypto-collateralized stablecoin maintained by MakerDAO.",
    tags: ["Stablecoin", "DeFi", "Decentralized"],
    website: "https://makerdao.com/dai",
  },
  PYUSD: {
    name: "PayPal USD",
    description: "PayPal's dollar-backed stablecoin issued on Ethereum and Solana.",
    tags: ["Stablecoin", "USD", "PayPal"],
    website: "https://paypal.com",
  },
  WLD: {
    name: "Worldcoin",
    description: "Identity and financial network using iris biometrics to prove unique humanity.",
    tags: ["Identity", "AI", "Ethereum"],
    website: "https://worldcoin.org",
  },
  FET: {
    name: "Fetch.ai",
    description: "AI-powered autonomous agent network for decentralized machine learning tasks.",
    tags: ["AI", "DeFi", "Agents"],
    website: "https://fetch.ai",
  },
  RNDR: {
    name: "Render",
    description: "Decentralized GPU rendering network connecting artists with idle GPU power.",
    tags: ["AI", "DePIN", "GPU"],
    website: "https://rendernetwork.com",
  },
  TAO: {
    name: "Bittensor",
    description: "Decentralized machine learning network where nodes are rewarded for AI predictions.",
    tags: ["AI", "Layer 1", "Decentralized ML"],
    website: "https://bittensor.com",
  },
  INJ: {
    name: "Injective",
    description: "Layer-1 DeFi blockchain for decentralized derivatives and prediction markets.",
    tags: ["Layer 1", "DeFi", "Derivatives"],
    website: "https://injective.com",
  },
  SUI: {
    name: "Sui",
    description: "Move-based blockchain designed for high throughput and instant finality.",
    tags: ["Layer 1", "Move", "High Speed"],
    website: "https://sui.io",
  },
  APT: {
    name: "Aptos",
    description: "Safe, scalable Layer-1 built with the Move programming language from Meta.",
    tags: ["Layer 1", "Move", "PoS"],
    website: "https://aptoslabs.com",
  },
  SEI: {
    name: "Sei",
    description: "First sector-specific Layer-1 blockchain built for trading applications.",
    tags: ["Layer 1", "Trading", "Cosmos"],
    website: "https://sei.io",
  },
  TIA: {
    name: "Celestia",
    description: "Modular blockchain providing a scalable data availability layer for rollups.",
    tags: ["Modular", "Data Availability", "Layer 0"],
    website: "https://celestia.org",
  },
  JUP: {
    name: "Jupiter",
    description: "Leading DEX aggregator on Solana offering best-route swaps across all liquidity.",
    tags: ["DeFi", "DEX", "Solana"],
    website: "https://jup.ag",
  },
  PYTH: {
    name: "Pyth Network",
    description: "High-fidelity oracle network delivering real-time market data for DeFi.",
    tags: ["Oracle", "DeFi Infrastructure", "Solana"],
    website: "https://pyth.network",
  },
  W: {
    name: "Wormhole",
    description: "Cross-chain messaging protocol connecting 30+ blockchains for asset bridging.",
    tags: ["Bridge", "Interoperability", "Multichain"],
    website: "https://wormhole.com",
  },
  STRK: {
    name: "Starknet",
    description: "Ethereum Layer-2 using STARK zero-knowledge proofs for scalable computation.",
    tags: ["Layer 2", "ZK Rollup", "Ethereum"],
    website: "https://starknet.io",
  },
  MANTA: {
    name: "Manta Network",
    description: "Modular L2 with native ZK privacy and ecosystem incentive programs.",
    tags: ["Layer 2", "Privacy", "ZK"],
    website: "https://manta.network",
  },
  XMR: {
    name: "Monero",
    description: "Privacy-focused cryptocurrency with ring signatures and stealth addresses.",
    tags: ["Privacy", "PoW", "Layer 1"],
    website: "https://getmonero.org",
  },
  ZEC: {
    name: "Zcash",
    description: "Privacy coin using zk-SNARKs for shielded transactions with optional transparency.",
    tags: ["Privacy", "PoW", "Layer 1"],
    website: "https://z.cash",
  },
  FIL: {
    name: "Filecoin",
    description: "Decentralized storage network where users rent out spare hard drive space.",
    tags: ["DePIN", "Storage", "Layer 1"],
    website: "https://filecoin.io",
  },
  AR: {
    name: "Arweave",
    description: "Permanent, censorship-resistant data storage through one-time payment.",
    tags: ["DePIN", "Storage", "Permanent Web"],
    website: "https://arweave.org",
  },
  HNT: {
    name: "Helium",
    description: "Decentralized physical wireless network for IoT devices using blockchain incentives.",
    tags: ["DePIN", "IoT", "Wireless"],
    website: "https://helium.com",
  },
  IOTX: {
    name: "IoTeX",
    description: "Decentralized infrastructure connecting smart devices to blockchain.",
    tags: ["DePIN", "IoT", "Layer 1"],
    website: "https://iotex.io",
  },
  CRO: {
    name: "Cronos",
    description: "EVM-compatible chain by Crypto.com for DeFi and payments at low cost.",
    tags: ["Layer 1", "Exchange Chain", "EVM"],
    website: "https://cronos.org",
  },
  OKB: {
    name: "OKB",
    description: "Utility and governance token of the OKX exchange and OKX Chain ecosystem.",
    tags: ["Exchange Token", "Layer 1", "EVM"],
    website: "https://okx.com",
  },
  CHZ: {
    name: "Chiliz",
    description: "Sports and entertainment blockchain enabling fan tokens for global clubs.",
    tags: ["Sports", "Fan Tokens", "Layer 1"],
    website: "https://chiliz.com",
  },
  ENJ: {
    name: "Enjin",
    description: "Blockchain ecosystem for creating, trading, and integrating NFT game items.",
    tags: ["Gaming", "NFT", "Ethereum"],
    website: "https://enjin.io",
  },
  GALA: {
    name: "Gala Games",
    description: "Blockchain gaming platform where players earn GALA by playing P2E games.",
    tags: ["Gaming", "NFT", "Play-to-Earn"],
    website: "https://gala.games",
  },
  GMT: {
    name: "STEPN",
    description: "Move-to-earn fitness app where users earn tokens by walking, jogging, or running.",
    tags: ["Move-to-Earn", "DeFi", "Lifestyle"],
    website: "https://stepn.com",
  },
  ROSE: {
    name: "Oasis Network",
    description: "Privacy-first Layer-1 blockchain enabling confidential smart contracts.",
    tags: ["Privacy", "Layer 1", "PoS"],
    website: "https://oasisprotocol.org",
  },
  KSM: {
    name: "Kusama",
    description: "Polkadot's canary network — a live, unaudited testbed for new parachain ideas.",
    tags: ["Layer 0", "Polkadot", "Experimental"],
    website: "https://kusama.network",
  },
  WAVES: {
    name: "Waves",
    description: "All-in-one blockchain for creating tokens, dApps, and decentralized exchanges.",
    tags: ["Layer 1", "PoS", "Token Issuance"],
    website: "https://waves.tech",
  },
  ZIL: {
    name: "Zilliqa",
    description: "Sharded Layer-1 blockchain enabling high transaction throughput for enterprises.",
    tags: ["Layer 1", "Sharding", "Enterprise"],
    website: "https://zilliqa.com",
  },
  KAVA: {
    name: "Kava",
    description: "DeFi-focused Layer-1 combining Ethereum and Cosmos ecosystems.",
    tags: ["DeFi", "Layer 1", "Cosmos"],
    website: "https://kava.io",
  },
  CELO: {
    name: "Celo",
    description: "Mobile-first blockchain for fast, borderless payments using phone numbers as addresses.",
    tags: ["Payments", "Mobile", "Layer 1"],
    website: "https://celo.org",
  },
  ONE: {
    name: "Harmony",
    description: "Fast, open blockchain for decentralized apps with 2-second finality.",
    tags: ["Layer 1", "Sharding", "PoS"],
    website: "https://harmony.one",
  },
  ICX: {
    name: "ICON",
    description: "Blockchain interoperability platform connecting independent blockchains across Korea.",
    tags: ["Interoperability", "Layer 1", "DPoS"],
    website: "https://icon.foundation",
  },
  IOTA: {
    name: "IOTA",
    description: "Feeless distributed ledger for IoT data integrity and machine-to-machine payments.",
    tags: ["DePIN", "IoT", "DAG"],
    website: "https://iota.org",
  },
  STX: {
    name: "Stacks",
    description: "Smart contract Layer-2 on Bitcoin enabling DeFi and NFTs secured by BTC PoW.",
    tags: ["Layer 2", "Bitcoin", "Smart Contracts"],
    website: "https://stacks.co",
  },
  RUNE: {
    name: "THORChain",
    description: "Decentralized cross-chain liquidity network for native asset swaps without wrapping.",
    tags: ["DeFi", "Bridge", "Cross-Chain"],
    website: "https://thorchain.org",
  },
  OSMO: {
    name: "Osmosis",
    description: "AMM DEX built for the Cosmos IBC ecosystem with customizable liquidity pools.",
    tags: ["DeFi", "DEX", "Cosmos"],
    website: "https://osmosis.zone",
  },
  DYDX: {
    name: "dYdX",
    description: "Decentralized derivatives exchange for perpetual contracts with deep liquidity.",
    tags: ["DeFi", "Derivatives", "Layer 1"],
    website: "https://dydx.exchange",
  },
  GMX: {
    name: "GMX",
    description: "Decentralized perpetuals and spot exchange with zero-price-impact trades.",
    tags: ["DeFi", "Derivatives", "Arbitrum"],
    website: "https://gmx.io",
  },
  PENDLE: {
    name: "Pendle",
    description: "Yield trading protocol allowing users to split and trade future yield as tokens.",
    tags: ["DeFi", "Yield", "Ethereum"],
    website: "https://pendle.finance",
  },
  ENA: {
    name: "Ethena",
    description: "Synthetic dollar protocol backed by crypto delta-neutral hedging strategies.",
    tags: ["DeFi", "Stablecoin", "Ethereum"],
    website: "https://ethena.fi",
  },
  EIGEN: {
    name: "EigenLayer",
    description: "Restaking protocol extending Ethereum's cryptoeconomic security to new networks.",
    tags: ["DeFi", "Restaking", "Ethereum"],
    website: "https://eigenlayer.xyz",
  },
  IO: {
    name: "io.net",
    description: "Decentralized GPU computing network for AI/ML workloads at lower cost.",
    tags: ["AI", "DePIN", "GPU"],
    website: "https://io.net",
  },
  BOME: {
    name: "Book of Meme",
    description: "Solana meme coin built around storing internet memes on-chain permanently.",
    tags: ["Meme", "Solana"],
  },
  NOT: {
    name: "Notcoin",
    description: "Telegram-native play-to-earn token that onboarded millions into crypto via gaming.",
    tags: ["Gaming", "TON", "Play-to-Earn"],
    website: "https://notcoin.app",
  },
  TON: {
    name: "Toncoin",
    description: "The Open Network — Telegram's blockchain for fast, scalable mass-adoption Web3.",
    tags: ["Layer 1", "Telegram", "PoS"],
    website: "https://ton.org",
  },
  MEME: {
    name: "Memecoin",
    description: "Community-driven meme token representing the internet's love for crypto humor.",
    tags: ["Meme", "Ethereum"],
  },
  JASMY: {
    name: "JasmyCoin",
    description: "Japanese blockchain project enabling user-controlled personal data storage.",
    tags: ["DePIN", "Data Privacy", "IoT"],
    website: "https://jasmy.co.jp",
  },
  FLOW: {
    name: "Flow",
    description: "Fast, developer-friendly blockchain created by Dapper Labs for NFTs and gaming.",
    tags: ["Layer 1", "NFT", "Gaming"],
    website: "https://flow.com",
  },
  THETA: {
    name: "Theta Network",
    description: "Decentralized video streaming network where users earn by sharing bandwidth.",
    tags: ["Media", "DePIN", "Streaming"],
    website: "https://thetatoken.org",
  },
  NEO: {
    name: "NEO",
    description: "China's leading smart contract platform dubbed the 'Ethereum of China'.",
    tags: ["Layer 1", "Smart Contracts", "dBFT"],
    website: "https://neo.org",
  },
  WAN: {
    name: "Wanchain",
    description: "Cross-chain infrastructure enabling interoperability between all major blockchains.",
    tags: ["Interoperability", "Bridge", "Layer 1"],
    website: "https://wanchain.org",
  },
  EOS: {
    name: "EOS",
    description: "High-performance DPoS blockchain for enterprise dApps and commercial use.",
    tags: ["Layer 1", "DPoS", "Enterprise"],
    website: "https://eosnetwork.com",
  },
  QTUM: {
    name: "Qtum",
    description: "Hybrid blockchain merging Bitcoin's UTXO model with Ethereum smart contracts.",
    tags: ["Layer 1", "Smart Contracts", "PoS"],
    website: "https://qtum.org",
  },
  NANO: {
    name: "Nano",
    description: "Feeless, instant digital currency using a block-lattice data structure.",
    tags: ["Payments", "Feeless", "Layer 1"],
    website: "https://nano.org",
  },
  BAT: {
    name: "Basic Attention Token",
    description: "Token rewarding users for attention in the Brave privacy browser ecosystem.",
    tags: ["Attention Economy", "Browser", "Ethereum"],
    website: "https://basicattentiontoken.org",
  },
  ZRX: {
    name: "0x Protocol",
    description: "Decentralized exchange infrastructure enabling peer-to-peer ERC-20 trading.",
    tags: ["DeFi", "DEX", "Infrastructure"],
    website: "https://0x.org",
  },
  OCEAN: {
    name: "Ocean Protocol",
    description: "Decentralized marketplace for data and AI services with privacy-preserving tech.",
    tags: ["AI", "Data Marketplace", "DeFi"],
    website: "https://oceanprotocol.com",
  },
  AGIX: {
    name: "SingularityNET",
    description: "Decentralized marketplace for AI services and algorithms.",
    tags: ["AI", "Marketplace", "Ethereum"],
    website: "https://singularitynet.io",
  },
  OM: {
    name: "MANTRA",
    description: "RWA Layer-1 blockchain built for regulatory-compliant tokenized assets.",
    tags: ["RWA", "Layer 1", "Cosmos"],
    website: "https://mantrachain.io",
  },
  ONDO: {
    name: "Ondo Finance",
    description: "Institutional DeFi protocol for tokenizing US Treasury Bills and real-world assets.",
    tags: ["RWA", "DeFi", "Institutional"],
    website: "https://ondo.finance",
  },
  PAXG: {
    name: "PAX Gold",
    description: "Gold-backed stablecoin where each token represents one fine troy ounce of gold.",
    tags: ["RWA", "Stablecoin", "Gold"],
    website: "https://paxos.com/paxgold",
  },
  CKB: {
    name: "Nervos Network",
    description: "Modular blockchain with a PoW Layer-1 and unlimited Layer-2 scalability.",
    tags: ["Layer 1", "PoW", "Modular"],
    website: "https://nervos.org",
  },
  ANKR: {
    name: "Ankr",
    description: "Decentralized cloud computing platform providing Web3 infrastructure globally.",
    tags: ["DePIN", "Infrastructure", "Multi-chain"],
    website: "https://ankr.com",
  },
  BAND: {
    name: "Band Protocol",
    description: "Cross-chain oracle platform aggregating real-world data for Web3 applications.",
    tags: ["Oracle", "Cosmos", "DeFi Infrastructure"],
    website: "https://bandprotocol.com",
  },
  RAY: {
    name: "Raydium",
    description: "Automated market maker built on Solana providing liquidity to the Serum DEX.",
    tags: ["DeFi", "DEX", "Solana"],
    website: "https://raydium.io",
  },
  ORCA: {
    name: "Orca",
    description: "User-friendly DEX on Solana with concentrated liquidity pools (Whirlpools).",
    tags: ["DeFi", "DEX", "Solana"],
    website: "https://orca.so",
  },
  DRIFT: {
    name: "Drift Protocol",
    description: "Decentralized perpetuals and spot exchange on Solana with cross-margin accounts.",
    tags: ["DeFi", "Derivatives", "Solana"],
    website: "https://drift.trade",
  },
  MPLX: {
    name: "Metaplex",
    description: "NFT standard and marketplace infrastructure protocol for the Solana ecosystem.",
    tags: ["NFT", "Infrastructure", "Solana"],
    website: "https://metaplex.com",
  },
};

const TAG_COLORS: Record<string, string> = {
  "Layer 1":           "bg-blue-500/15 text-blue-400 border-blue-500/20",
  "Layer 2":           "bg-violet-500/15 text-violet-400 border-violet-500/20",
  "Layer 0":           "bg-indigo-500/15 text-indigo-400 border-indigo-500/20",
  "DeFi":              "bg-green-500/15 text-green-400 border-green-500/20",
  "DEX":               "bg-emerald-500/15 text-emerald-400 border-emerald-500/20",
  "Stablecoin":        "bg-teal-500/15 text-teal-400 border-teal-500/20",
  "Meme":              "bg-yellow-500/15 text-yellow-400 border-yellow-500/20",
  "NFT":               "bg-pink-500/15 text-pink-400 border-pink-500/20",
  "Gaming":            "bg-purple-500/15 text-purple-400 border-purple-500/20",
  "Metaverse":         "bg-fuchsia-500/15 text-fuchsia-400 border-fuchsia-500/20",
  "AI":                "bg-cyan-500/15 text-cyan-400 border-cyan-500/20",
  "DePIN":             "bg-orange-500/15 text-orange-400 border-orange-500/20",
  "Oracle":            "bg-sky-500/15 text-sky-400 border-sky-500/20",
  "Privacy":           "bg-gray-500/15 text-gray-400 border-gray-500/20",
  "Payments":          "bg-lime-500/15 text-lime-400 border-lime-500/20",
  "RWA":               "bg-amber-500/15 text-amber-400 border-amber-500/20",
  "Bridge":            "bg-rose-500/15 text-rose-400 border-rose-500/20",
  "Interoperability":  "bg-indigo-500/15 text-indigo-400 border-indigo-500/20",
  "Exchange Token":    "bg-yellow-600/15 text-yellow-500 border-yellow-600/20",
  "PoW":               "bg-orange-700/15 text-orange-400 border-orange-700/20",
  "PoS":               "bg-green-700/15 text-green-400 border-green-700/20",
  "Store of Value":    "bg-yellow-500/15 text-yellow-400 border-yellow-500/20",
  "Cosmos":            "bg-blue-600/15 text-blue-400 border-blue-600/20",
  "Solana":            "bg-purple-600/15 text-purple-400 border-purple-600/20",
  "Ethereum":          "bg-violet-600/15 text-violet-400 border-violet-600/20",
  "Modular":           "bg-teal-600/15 text-teal-400 border-teal-600/20",
  "Derivatives":       "bg-red-500/15 text-red-400 border-red-500/20",
  "Liquid Staking":    "bg-sky-600/15 text-sky-400 border-sky-600/20",
  "Restaking":         "bg-sky-700/15 text-sky-300 border-sky-700/20",
  "Data Availability": "bg-indigo-600/15 text-indigo-400 border-indigo-600/20",
  "Sports":            "bg-red-600/15 text-red-400 border-red-600/20",
  "Enterprise":        "bg-slate-500/15 text-slate-400 border-slate-500/20",
  "Move":              "bg-teal-500/15 text-teal-400 border-teal-500/20",
  "Scaling":           "bg-blue-400/15 text-blue-300 border-blue-400/20",
  "Play-to-Earn":      "bg-green-600/15 text-green-400 border-green-600/20",
  "Supply Chain":      "bg-amber-600/15 text-amber-400 border-amber-600/20",
  "Yield":             "bg-lime-600/15 text-lime-400 border-lime-600/20",
  "GPU":               "bg-cyan-700/15 text-cyan-400 border-cyan-700/20",
  "Green":             "bg-emerald-600/15 text-emerald-400 border-emerald-600/20",
};

export function getCoinInfo(symbol: string): CoinInfo | undefined {
  return COIN_INFO[symbol.toUpperCase()];
}

export function getTagColor(tag: string): string {
  return TAG_COLORS[tag] ?? "bg-secondary text-muted-foreground border-border";
}

export default COIN_INFO;
