// AUTO-GENERATED by deploy-escrow-standalone.mjs — do not edit manually
// Deployed: 2026-05-02T12:21:04.721Z

import { parseAbi } from "viem";

export const ESCROW_ABI = parseAbi([
  "function lockETH(bytes32 orderId) external payable",
  "function lockERC20(bytes32 orderId, address token, uint256 amount) external",
  "function release(bytes32 orderId, address recipient) external",
  "function cancel(bytes32 orderId) external",
  "function getDeposit(bytes32 orderId) external view returns (address depositor, address token, uint256 amount, uint64 lockedAt, bool released)",
  "function getDepositorOrders(address depositor) external view returns (bytes32[])",
  "event OrderLocked(bytes32 indexed orderId, address indexed depositor, address indexed token, uint256 amount)",
  "event OrderReleased(bytes32 indexed orderId, address indexed recipient, address token, uint256 amount)",
  "event OrderCancelled(bytes32 indexed orderId, address indexed depositor, address token, uint256 amount)",
]);

/** Escrow contract address per EVM chainId */
export const ESCROW_ADDRESSES: Record<number, string> = {
  11155111: "0x4deb6023abD9E1C640aDa35201be8ff591d21cF2",  // Sepolia testnet
};

/** The OrahDEX relayer address that can release / cancel escrow deposits */
export const RELAYER_ADDRESS = "0x67C7f23eE49B6417661748F23F743C0B274039e2";

export const ESCROW_CHAIN_ID = 11155111;
