// AUTO-GENERATED by deploy-escrow-standalone.mjs — do not edit manually
// Last update: 2026-05-17T04:16:10.458Z

import { parseAbi } from "viem";

// MUST use parseAbi() — viem's encodeFunctionData throws silently on raw strings.
export const ESCROW_ABI = parseAbi([
  "function lockETH(bytes32 orderId) external payable",
  "function lockERC20(bytes32 orderId, address token, uint256 amount) external",
  "function release(bytes32 orderId, address recipient) external",
  "function cancel(bytes32 orderId) external",
  "function getDeposit(bytes32 orderId) external view returns (address depositor, address token, uint256 amount, uint64 lockedAt, bool released)",
  "function getDepositorOrders(address depositor) external view returns (bytes32[])",
  "event OrderLocked(bytes32 indexed orderId, address indexed depositor, address indexed token, uint256 amount)",
  "event OrderReleased(bytes32 indexed orderId, address indexed recipient, address token, uint256 amount)",
  "event OrderCancelled(bytes32 indexed orderId, address indexed depositor, address token, uint256 amount)",
]);

/** Escrow contract address per EVM chainId. Populated as each chain is deployed. */
export const ESCROW_ADDRESSES: Record<number, string> = {
  1:      "0xeE234cEb85697b64800E696699b7841e00413B4f",  // Ethereum
  10:     "0xeE234cEb85697b64800E696699b7841e00413B4f",  // Optimism
  56:     "0xeE234cEb85697b64800E696699b7841e00413B4f",  // BSC
  130:    "0xeE234cEb85697b64800E696699b7841e00413B4f",  // Unichain
  137:    "0xeE234cEb85697b64800E696699b7841e00413B4f",  // Polygon
  1329:   "0xeE234cEb85697b64800E696699b7841e00413B4f",  // Sei
  43114:  "0xeE234cEb85697b64800E696699b7841e00413B4f",  // Avalanche
  59144:  "0xeE234cEb85697b64800E696699b7841e00413B4f",  // Linea
  534352: "0xeE234cEb85697b64800E696699b7841e00413B4f",  // Scroll
  11155111: "0x4deb6023abD9E1C640aDa35201be8ff591d21cF2",  // Sepolia
};

/** The OrahDEX relayer address that can release / cancel escrow deposits. */
export const RELAYER_ADDRESS = "0x5A391a3A2d6d885C412FE24be624126694de08dA";

/** Default chainId used by legacy callers — first deployed chain. */
export const ESCROW_CHAIN_ID = 1;

/** Returns true when an escrow contract is deployed on the given chainId. */
export function isEscrowSupported(chainId: number): boolean {
  return chainId in ESCROW_ADDRESSES;
}
