/**
 * Dynamic market categorization.
 *
 * Maps every known base asset to one or more category tags.
 * These tags are used by Markets.tsx to populate the themed tabs
 * (MEME, AI, DeFi, Gaming, etc.) directly from live DB data,
 * so new pairs seeded into the database automatically appear in
 * the right tab without any manual list updates.
 *
 * A base asset may belong to multiple categories.
 * Tabs that are protocol-specific (zora, uniswap, pancake) or
 * use a non-standard quote asset (sol) continue to use their
 * existing mock symbol lists.
 */
export const BASE_CATEGORIES: Record<string, string[]> = {
  // ── Layer 1 blockchains ───────────────────────────────────────────────────
  BTC:   ["l1", "brc20"],
  ETH:   ["l1"],
  SOL:   ["l1", "sol_eco"],
  BNB:   ["l1", "exchange"],
  ADA:   ["l1"],
  XRP:   ["l1"],
  DOT:   ["l1"],
  AVAX:  ["l1"],
  MATIC: ["l1", "l2"],
  LTC:   ["l1"],
  BCH:   ["l1", "brc20"],
  BSV:   ["l1", "brc20"],
  DOGE:  ["l1", "meme"],
  TRX:   ["l1"],
  ETC:   ["l1"],
  EOS:   ["l1"],
  XLM:   ["l1"],
  XMR:   ["l1"],
  ZEC:   ["l1"],
  DASH:  ["l1"],
  ALGO:  ["l1"],
  HBAR:  ["l1"],
  VET:   ["l1"],
  THETA: ["l1", "depin"],
  NEAR:  ["l1"],
  APT:   ["l1"],
  SUI:   ["l1"],
  TON:   ["l1"],
  KAS:   ["l1"],
  NEO:   ["l1"],
  EGLD:  ["l1"],
  ONE:   ["l1"],
  FTM:   ["l1", "l2"],
  FLR:   ["l1"],
  CELO:  ["l1"],
  WAVES: ["l1"],
  ICX:   ["l1"],
  ZEN:   ["l1"],
  KDA:   ["l1"],
  XDC:   ["l1"],
  ROSE:  ["l1"],
  CFX:   ["l1"],
  CORE:  ["l1"],
  CKB:   ["l1"],
  ASTR:  ["l1"],
  ZIL:   ["l1"],
  ICP:   ["l1", "depin"],
  IOTX:  ["l1", "depin"],
  FIL:   ["l1", "depin"],
  // ── Layer 2 / scaling ─────────────────────────────────────────────────────
  ARB:   ["l2"],
  OP:    ["l2"],
  MNT:   ["l2"],
  ZK:    ["l2"],
  SCR:   ["l2"],
  STRK:  ["l2"],
  IMX:   ["l2", "gaming"],
  METIS: ["l2"],
  BOBA:  ["l2"],
  ZRO:   ["l2"],
  EIGEN: ["l2"],
  W:     ["l2"],
  GLMR:  ["l2"],
  MOVR:  ["l2"],
  DYM:   ["l2", "cosmos"],
  STX:   ["l2", "brc20"],
  AERO:  ["l2"],
  SEAM:  ["l2", "defi"],
  MOONWELL: ["l2", "defi"],
  MORPHO:   ["l2", "defi"],
  // ── DeFi protocols ────────────────────────────────────────────────────────
  UNI:   ["defi"],
  AAVE:  ["defi"],
  MKR:   ["defi", "rwa"],
  CRV:   ["defi"],
  LDO:   ["defi"],
  COMP:  ["defi"],
  SNX:   ["defi"],
  YFI:   ["defi"],
  SUSHI: ["defi"],
  BAL:   ["defi"],
  DYDX:  ["defi"],
  GMX:   ["defi"],
  RUNE:  ["defi", "cosmos"],
  PENDLE:["defi"],
  CVX:   ["defi"],
  FXS:   ["defi", "rwa"],
  SPELL: ["defi"],
  PERP:  ["defi"],
  ENS:   ["defi"],
  GRT:   ["defi", "ai", "depin"],
  CAKE:  ["defi"],
  JUP:   ["defi", "sol_eco"],
  PYTH:  ["defi", "sol_eco"],
  RAY:   ["defi", "sol_eco"],
  ORCA:  ["defi", "sol_eco"],
  JTO:   ["defi", "sol_eco"],
  MSOL:  ["defi", "sol_eco"],
  RETH:  ["defi"],
  WBTC:  ["defi", "brc20"],
  CBETH: ["defi"],
  WSTETH:["defi"],
  QUICK: ["defi"],
  DFYN:  ["defi"],
  LINK:  ["defi"],
  OSMO:  ["defi", "cosmos"],
  LISTA: ["defi"],
  TNSR:  ["defi"],
  REZ:   ["defi"],
  MPL:   ["defi", "rwa"],
  // ── AI / ML tokens ────────────────────────────────────────────────────────
  FET:   ["ai", "depin"],
  AGIX:  ["ai"],
  OCEAN: ["ai", "depin"],
  RNDR:  ["ai", "depin"],
  TAO:   ["ai", "depin"],
  WLD:   ["ai"],
  ARKM:  ["ai"],
  CTXC:  ["ai"],
  NMR:   ["ai"],
  ORAI:  ["ai"],
  ALT:   ["ai", "l2"],
  GRASS: ["ai", "depin", "sol_eco"],
  // ── DePIN ─────────────────────────────────────────────────────────────────
  STORJ: ["depin"],
  GLM:   ["depin"],
  LPT:   ["depin"],
  BAND:  ["depin", "cosmos"],
  POWR:  ["depin"],
  // ── Meme coins ────────────────────────────────────────────────────────────
  SHIB:  ["meme"],
  PEPE:  ["meme"],
  FLOKI: ["meme"],
  TRUMP: ["meme"],
  BONK:  ["meme", "sol_eco"],
  WIF:   ["meme", "sol_eco"],
  POPCAT:["meme", "sol_eco"],
  BRETT: ["meme"],
  MOG:   ["meme"],
  TURBO: ["meme"],
  BOME:  ["meme", "sol_eco"],
  MEW:   ["meme", "sol_eco"],
  NEIRO: ["meme"],
  FWOG:  ["meme", "sol_eco"],
  MEME:  ["meme"],
  NOT:   ["meme"],
  HMSTR: ["meme"],
  DOGS:  ["meme"],
  NORMIE:["meme"],
  TOSHI: ["meme"],
  HIGHER:["meme"],
  DEGEN: ["meme"],
  LUNC:  ["meme", "cosmos"],
  RATS:  ["meme", "brc20"],
  SATS:  ["meme", "brc20"],
  COQ:   ["meme"],
  BTT:   ["meme"],
  CATI:  ["meme"],
  BALD:  ["meme"],
  ZEUS:  ["meme", "sol_eco"],
  SLERF: ["meme", "sol_eco"],
  BB:    ["meme"],
  // ── Gaming / Metaverse ────────────────────────────────────────────────────
  AXS:   ["gaming"],
  SAND:  ["gaming"],
  MANA:  ["gaming"],
  ENJ:   ["gaming"],
  GALA:  ["gaming"],
  RON:   ["gaming"],
  ILV:   ["gaming"],
  BEAM:  ["gaming", "l2"],
  PRIME: ["gaming"],
  PIXEL: ["gaming", "sol_eco"],
  BIGTIME:["gaming"],
  MC:    ["gaming"],
  ALICE: ["gaming"],
  WAXP:  ["gaming"],
  TLM:   ["gaming"],
  SLP:   ["gaming"],
  GODS:  ["gaming"],
  GHST:  ["gaming"],
  MAGIC: ["gaming"],
  // ── Cosmos ecosystem ──────────────────────────────────────────────────────
  ATOM:  ["l1", "cosmos"],
  INJ:   ["l1", "cosmos"],
  TIA:   ["l1", "cosmos"],
  SEI:   ["l1", "cosmos"],
  KAVA:  ["l1", "cosmos"],
  KSM:   ["cosmos"],
  ACA:   ["cosmos"],
  PHA:   ["cosmos"],
  JUNO:  ["cosmos"],
  SCRT:  ["cosmos"],
  STRD:  ["cosmos"],
  STARS: ["cosmos"],
  NTRN:  ["cosmos"],
  LUNA:  ["cosmos"],
  EVMOS: ["cosmos", "l2"],
  // ── Real World Assets (RWA) ───────────────────────────────────────────────
  PAXG:  ["rwa"],
  XAUT:  ["rwa"],
  ONDO:  ["rwa"],
  CFG:   ["rwa"],
  // ── Exchange tokens ───────────────────────────────────────────────────────
  OKB:   ["exchange"],
  CRO:   ["exchange"],
  KCS:   ["exchange"],
  GT:    ["exchange"],
  HT:    ["exchange"],
  BGB:   ["exchange"],
  WBT:   ["exchange"],
  // ── BRC-20 / Bitcoin ecosystem ────────────────────────────────────────────
  ORDI:  ["brc20"],
  CBBTC: ["brc20"],
  // ── Solana ecosystem extras ───────────────────────────────────────────────
  HNT:   ["depin", "sol_eco"],
  STEP:  ["sol_eco"],
  SAMO:  ["sol_eco"],
};

/** Return all category tags for a given base asset. */
export function getCategories(base: string): string[] {
  return BASE_CATEGORIES[base.toUpperCase()] ?? [];
}

/** Check if a base asset belongs to a specific category. */
export function hasCategory(base: string, tag: string): boolean {
  return getCategories(base).includes(tag);
}
