import crypto from "node:crypto";
import { privateKeyToAccount } from "viem/accounts";
const pk = "0x" + crypto.randomBytes(32).toString("hex");
const acct = privateKeyToAccount(pk as `0x${string}`);
console.log("════════════════════════════════════════════════════════════════════");
console.log("NEW EXCHANGE HOT WALLET GENERATED");
console.log("════════════════════════════════════════════════════════════════════");
console.log("Address (public — fund this):", acct.address);
console.log("Private key (SECRET):        ", pk);
console.log("════════════════════════════════════════════════════════════════════");
console.log("Add the private key to Replit Secrets as: EXCHANGE_HOT_WALLET_KEY");
console.log("Also add a strong random string as:      EVM_WALLET_SECRET");
console.log("(EVM_WALLET_SECRET protects future server-generated keys.");
console.log(" NEVER delete it once set, or all encrypted DB keys become unrecoverable.)");
