import { pgTable, text, integer, timestamp, index } from "drizzle-orm/pg-core";

/**
 * HTLC Registry — persistent record of every cross-chain HTLC output
 * generated by OrahDEX settlement layer (BSV Settlement v2).
 *
 * This table is the authoritative, restart-safe source of truth for the
 * htlcWatcher service. On boot, htlcWatcher hydrates its in-memory registry
 * from rows where status is NOT a terminal state (CLAIMED / REFUNDED).
 *
 * Terminal states: CLAIMED, REFUNDED
 * Non-terminal:    LOCKED, EXPIRED, UNKNOWN
 */
export const htlcRegistryTable = pgTable("htlc_registry", {
  /** Unique trade ID — same value used as the order's primary key */
  tradeId:         text("trade_id").primaryKey(),
  /** BSV P2SH address of the HTLC output */
  htlcAddress:     text("htlc_address").notNull(),
  /** SHA-256d secret hash embedded in the redeem script */
  secretHash:      text("secret_hash").notNull(),
  /** Absolute BSV block height for the CLTV refund locktime */
  locktimeBlocks:  integer("locktime_blocks").notNull(),
  /** BSV settlement txid (OP_RETURN + P2SH transaction) */
  settlementTxid:  text("settlement_txid").notNull(),
  /** Trading pair e.g. "ETH/BSV" */
  pair:            text("pair").notNull(),
  /** Wallet address of the trader on the non-BSV chain */
  userAddress:     text("user_address").notNull(),
  /**
   * Current lifecycle status.
   * LOCKED   — HTLC output is funded, awaiting claim or expiry.
   * EXPIRED  — Locktime passed, UTXO still present — refund available.
   * CLAIMED  — Relayer revealed secret, swap complete. TERMINAL.
   * REFUNDED — User swept via CLTV. TERMINAL.
   * UNKNOWN  — Never funded or chain API unreachable.
   */
  status:          text("status").notNull().default("LOCKED"),
  /** Txid of the spend (set when CLAIMED or REFUNDED) */
  spendTxid:       text("spend_txid"),
  createdAt:       timestamp("created_at").notNull().defaultNow(),
  updatedAt:       timestamp("updated_at").notNull().defaultNow(),
}, (t) => [
  index("htlc_registry_address_idx").on(t.htlcAddress),
  index("htlc_registry_status_idx").on(t.status),
  index("htlc_registry_user_idx").on(t.userAddress),
]);

/**
 * HTLC Events — immutable log of every status transition for every HTLC.
 *
 * Append-only. Each row records a single LOCKED→CLAIMED, LOCKED→EXPIRED,
 * or EXPIRED→REFUNDED transition, with the on-chain evidence (block height,
 * spend txid). This table survives server restarts and lets the relayer-events
 * endpoint serve full historical data rather than just what happened since
 * the last process boot.
 */
export const htlcEventsTable = pgTable("htlc_events", {
  id:             text("id").primaryKey(),             // nanoid / uuid v4 — set by app
  tradeId:        text("trade_id").notNull(),
  htlcAddress:    text("htlc_address").notNull(),
  settlementTxid: text("settlement_txid").notNull(),
  pair:           text("pair").notNull(),
  /** Status before the transition */
  fromStatus:     text("from_status").notNull(),
  /** Status after the transition */
  toStatus:       text("to_status").notNull(),
  /** BSV txid that caused the transition (spend tx for CLAIMED/REFUNDED) */
  spendTxid:      text("spend_txid"),
  /** BSV block height at time of detection */
  blockHeight:    integer("block_height").notNull().default(0),
  createdAt:      timestamp("created_at").notNull().defaultNow(),
}, (t) => [
  index("htlc_events_trade_idx").on(t.tradeId),
  index("htlc_events_address_idx").on(t.htlcAddress),
  index("htlc_events_created_idx").on(t.createdAt),
]);
