import { pgTable, text, integer, timestamp, index } from "drizzle-orm/pg-core";

/**
 * HTLC Registry — persistent record of every cross-chain HTLC output
 * generated by Orah settlement layer (BSV Settlement v2).
 *
 * ── New fields (v3) ───────────────────────────────────────────────────────────
 *
 *   terminalAt   — timestamp when the HTLC reached a terminal state
 *                  (CLAIMED or REFUNDED). NULL while non-terminal.
 *                  Enables: fast "recently resolved" queries, keeper scoring
 *                  windows, and row-purge schedules.
 *
 *   nextCheckAt  — the earliest timestamp at which the watcher should re-poll
 *                  this HTLC. Adaptive: HTLCs near locktime are polled more
 *                  often; HTLCs far from locktime are polled less often.
 *                  Persisted so a restart respects the existing schedule.
 *
 *                  Adaptive schedule:
 *                    status=EXPIRED  →  15 s  (urgent — refund window open)
 *                    blocksLeft ≤ 6  →  30 s  (~1 h of BSV time)
 *                    blocksLeft ≤ 24 →  60 s  (~4 h of BSV time)
 *                    default         →  90 s
 *
 * Terminal states: CLAIMED, REFUNDED
 * Non-terminal:    LOCKED, EXPIRED, UNKNOWN
 */
export const htlcRegistryTable = pgTable("htlc_registry", {
  tradeId:         text("trade_id").primaryKey(),
  htlcAddress:     text("htlc_address").notNull(),
  secretHash:      text("secret_hash").notNull(),
  locktimeBlocks:  integer("locktime_blocks").notNull(),
  settlementTxid:  text("settlement_txid").notNull(),
  pair:            text("pair").notNull(),
  userAddress:     text("user_address").notNull(),
  /**
   * LOCKED   — HTLC output is funded, awaiting claim or expiry.
   * EXPIRED  — Locktime passed, UTXO still present — refund available.
   * CLAIMED  — Relayer revealed secret, swap complete. TERMINAL.
   * REFUNDED — User swept via CLTV. TERMINAL.
   * UNKNOWN  — Never funded or chain API unreachable.
   */
  status:          text("status").notNull().default("LOCKED"),
  spendTxid:       text("spend_txid"),
  /** Set when status transitions to CLAIMED or REFUNDED. NULL while active. */
  terminalAt:      timestamp("terminal_at"),
  /** Next poll timestamp — drives adaptive polling schedule. */
  nextCheckAt:     timestamp("next_check_at").notNull().defaultNow(),
  createdAt:       timestamp("created_at").notNull().defaultNow(),
  updatedAt:       timestamp("updated_at").notNull().defaultNow(),
}, (t) => [
  index("htlc_registry_address_idx").on(t.htlcAddress),
  index("htlc_registry_status_idx").on(t.status),
  index("htlc_registry_user_idx").on(t.userAddress),
  index("htlc_registry_next_check_idx").on(t.nextCheckAt),
  index("htlc_registry_terminal_idx").on(t.terminalAt),
]);

/**
 * HTLC Events — immutable append-only log of every status transition.
 *
 * One row per state change: LOCKED→CLAIMED, LOCKED→EXPIRED, EXPIRED→REFUNDED.
 * Includes on-chain evidence (block height, spend txid).
 *
 * Use cases:
 *   • Audit trail
 *   • Keeper reputation scoring
 *   • Settlement analytics dashboards
 *   • "Book of Cross-Chain Deeds"
 */
export const htlcEventsTable = pgTable("htlc_events", {
  id:             text("id").primaryKey(),
  tradeId:        text("trade_id").notNull(),
  htlcAddress:    text("htlc_address").notNull(),
  settlementTxid: text("settlement_txid").notNull(),
  pair:           text("pair").notNull(),
  fromStatus:     text("from_status").notNull(),
  toStatus:       text("to_status").notNull(),
  spendTxid:      text("spend_txid"),
  blockHeight:    integer("block_height").notNull().default(0),
  createdAt:      timestamp("created_at").notNull().defaultNow(),
}, (t) => [
  index("htlc_events_trade_idx").on(t.tradeId),
  index("htlc_events_address_idx").on(t.htlcAddress),
  index("htlc_events_created_idx").on(t.createdAt),
]);

/**
 * Keeper Actions — log of every action a Keeper takes on an HTLC.
 *
 * This is the foundation of the Keeper reputation system. Every time the
 * watcher detects that a Keeper was notified of a transition, or a Keeper
 * actively claims or refunds an HTLC, a row is inserted here.
 *
 * Action types:
 *   OBSERVED — Keeper was notified of the transition (all registered Relayers)
 *   CLAIMED  — Keeper revealed the preimage and swept the P2SH output
 *   REFUNDED — Keeper triggered the CLTV refund on behalf of the user
 *
 * Future extensions:
 *   • SKIPPED  — Keeper was eligible but did not act within a time window
 *   • DISPUTED — Keeper submitted an incorrect claim (slashing candidate)
 *
 * Scoring inputs:
 *   • timeliness (createdAt vs. HTLC createdAt)
 *   • accuracy (action matches expected outcome)
 *   • volume (count of HTLCs handled in a window)
 *   • value (HTLC sat amount, when tracked)
 */
export const keeperActionsTable = pgTable("keeper_actions", {
  id:            text("id").primaryKey(),
  keeperAddress: text("keeper_address").notNull(),
  htlcAddress:   text("htlc_address").notNull(),
  tradeId:       text("trade_id").notNull(),
  pair:          text("pair").notNull(),
  /**
   * OBSERVED — notification was sent to this Relayer Keeper
   * CLAIMED  — Keeper swept the HTLC via the claim path
   * REFUNDED — Keeper triggered or observed the CLTV refund
   */
  action:        text("action").notNull(),
  /** BSV txid of the action (spend tx for CLAIMED/REFUNDED, null for OBSERVED) */
  txid:          text("txid"),
  /** Block height at time of detection */
  blockHeight:   integer("block_height").notNull().default(0),
  createdAt:     timestamp("created_at").notNull().defaultNow(),
}, (t) => [
  index("keeper_actions_keeper_idx").on(t.keeperAddress),
  index("keeper_actions_htlc_idx").on(t.htlcAddress),
  index("keeper_actions_created_idx").on(t.createdAt),
  index("keeper_actions_action_idx").on(t.action),
]);
