import { ethers, network } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  const chainId    = Number((await ethers.provider.getNetwork()).chainId);

  console.log(`\n=== OrahDEXEscrow Deployment ===`);
  console.log(`Network:  ${network.name} (chainId: ${chainId})`);
  console.log(`Deployer / Relayer: ${deployer.address}`);
  console.log(`Balance:  ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH\n`);

  // The relayer is the deployer for testnet.
  // On mainnet this should be a dedicated hot-wallet managed by the backend.
  const relayerAddress = deployer.address;

  console.log("[1/1] Deploying OrahDEXEscrow...");
  const Escrow  = await ethers.getContractFactory("OrahDEXEscrow");
  const escrow  = await Escrow.deploy(relayerAddress);
  await escrow.waitForDeployment();
  const escrowAddr = await escrow.getAddress();
  console.log(`      OrahDEXEscrow deployed at: ${escrowAddr}`);

  // Persist alongside existing deployment info
  const deploymentsDir = path.join(__dirname, "..", "deployments");
  const deployFile     = path.join(deploymentsDir, `${chainId}.json`);
  let existing: Record<string, any> = {};
  if (fs.existsSync(deployFile)) {
    existing = JSON.parse(fs.readFileSync(deployFile, "utf8"));
  }
  const updated = {
    ...existing,
    escrow:   escrowAddr,
    relayer:  relayerAddress,
    updatedAt: new Date().toISOString(),
  };
  fs.mkdirSync(deploymentsDir, { recursive: true });
  fs.writeFileSync(deployFile, JSON.stringify(updated, null, 2));
  console.log(`Addresses saved → deployments/${chainId}.json`);

  // Sync to the frontend lib directory
  const frontendDir   = path.join(__dirname, "..", "..", "bsv-dex", "src", "lib", "deployments");
  fs.mkdirSync(frontendDir, { recursive: true });
  fs.writeFileSync(path.join(frontendDir, `${chainId}.json`), JSON.stringify(updated, null, 2));
  console.log(`Addresses synced → bsv-dex/src/lib/deployments/${chainId}.json`);

  // Also write a TypeScript module the frontend can import statically
  const escrowAbi = [
    "function lockETH(bytes32 orderId) external payable",
    "function lockERC20(bytes32 orderId, address token, uint256 amount) external",
    "function release(bytes32 orderId, address recipient) external",
    "function cancel(bytes32 orderId) external",
    "function getDeposit(bytes32 orderId) external view returns (tuple(address depositor, address token, uint256 amount, uint64 lockedAt, bool released))",
    "function getDepositorOrders(address depositor) external view returns (bytes32[])",
    "event OrderLocked(bytes32 indexed orderId, address indexed depositor, address indexed token, uint256 amount)",
    "event OrderReleased(bytes32 indexed orderId, address indexed recipient, address token, uint256 amount)",
    "event OrderCancelled(bytes32 indexed orderId, address indexed depositor, address token, uint256 amount)",
  ];

  const tsContent = `// AUTO-GENERATED by deploy-escrow.ts — do not edit manually
export const ESCROW_ABI = ${JSON.stringify(escrowAbi, null, 2)} as const;

export const ESCROW_ADDRESSES: Record<number, string> = {
  11155111: "${chainId === 11155111 ? escrowAddr : (existing.escrow ?? "")}",  // Sepolia
  84532:    "${chainId === 84532    ? escrowAddr : (existing.escrow ?? "")}",  // Base Sepolia
};

export const RELAYER_ADDRESS = "${relayerAddress}";
`;
  const tsOut = path.join(__dirname, "..", "..", "bsv-dex", "src", "lib", "escrowConfig.ts");
  fs.writeFileSync(tsOut, tsContent);
  console.log(`ABI + addresses → bsv-dex/src/lib/escrowConfig.ts`);

  console.log("\n✓ Deployment complete!");
  console.log(`Escrow:  ${escrowAddr}`);
  console.log(`Relayer: ${relayerAddress}`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => { console.error(err); process.exit(1); });
